### ISSUE TITLE
TTS button that is easily identified and accessible

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1000]

**Comment by benetechMatt** [comment]
![speaker icon](https://user-images.githubusercontent.com/49413678/75820094-5f483500-5d61-11ea-95d6-de43a1356d91.png) TTS available, not active

![pause icon in a circle](https://user-images.githubusercontent.com/49413678/75820116-666f4300-5d61-11ea-9e8c-d132a8a7cd3d.png) Pause / Stop TTS


![problem page mockup showing the TTS button next to each step, the "my work" section and prompt](https://user-images.githubusercontent.com/49413678/75820753-87846380-5d62-11ea-92da-b10a695bb5b1.png)

The button should have a 5 pixels padding around the icon and a black border that appears when the button is hovered over or selected.

**Comment by benetechMatt** [comment]
![inactive TTS button with hover state of a black border around the speaker icon with 5 pixels of padding](https://user-images.githubusercontent.com/49413678/75821061-2f9a2c80-5d63-11ea-857f-821fd2e39c48.png)

![active TTS button with hover state of a black border around the pause icon with 5 pixels of padding](https://user-images.githubusercontent.com/49413678/75821099-450f5680-5d63-11ea-961d-1acd9235d2dc.png)

**Comment by alexrcabral** [comment]
Button also needs a relevant label, e.g. "speak step" and "pause speaking"

**Comment by alexrcabral** [comment]
Dependent on open questions from #995

**Comment by alexrcabral** [comment]
@benetechMatt 
Update from #1001 : Since it restarts from the beginning, it should be a stop button rather than a pause button. Pause implies that it will start speaking from where it left off.

**Comment by benetechMatt** [comment]
Pause/stop button changing to a stop icon as shown https://github.com/benetech/MathShare/issues/1001#issuecomment-604165659

@alexrcabral @jscholes should the Speak labels be tailored to the use.  Speak step, speak prompt, speak text.  Or should all TTS buttons have the same "speak text"

For the stop button I'm assuming "stop speaking" works.

**Comment by alexrcabral** [comment]
See @bpmcneilly and @jscholes comments on #1001 

> For the individual step buttons, I just want to confirm that the accessible names for these icons buttons are unique for each step. 

>I'll defer to @jscholes here, but my gut reaction would be to name these buttons something like "Step [number] Text to Speech", and then use an aria-pressed attribute to toggle the state.

> @bpmcneilly Sounds good to me. Maybe "Speak Step N", if we're going for an actionable theme for button text. I like aria-pressed, because that update in state will be announced by a screen reader whereas a change in button text isn't guaranteed to be.

**Comment by jscholes** [comment]
@benetechMatt and @alexrcabral - Are you waiting for any further accessibility input from us on this one?

**Comment by benetechMatt** [comment]
@alexrcabral @jscholes From your comments I assume the following:

accessible name when speaking the prompt, "Speak prompt"

Accessible name when speaking the steps, "Speak step N"

Accessible name when speaking the My Work section, "Speak my work"

**Comment by jscholes** [comment]
@benetechMatt Correct, assuming that there can only ever be a single prompt and my work section.

**Comment by alexrcabral** [comment]
@jscholes Exactly -- only ever one prompt, only ever one "my work" section (which functions as the current active step). 

Just to confirm, we'll be using the aria-pressed attribute with the labels: 
- "Speak Prompt" for speaking the prompt
- "Speak Step N" for each given step 
- "Speak My Work" for the my work section denoting the current editable step

**Comment by jscholes** [comment]
@alexrcabral We've been thinking about this and discussing internally, and on reflection we feel two things are important to revisit here:

1. Explicit labels are going to be better than `aria-pressed`.  `aria-pressed` does indicate state, but not the semantics of the action to be carried out.  We think it would instead be better to describe what the button will do via a standard label.  The formats are fine, i.e. including the context for each one.  But there must be an action ("speak", "stop", pause").  Which brings me onto...
2. Apologies that I haven't picked up on this earlier, but there does need to be pause and stop controls.  A user who is relying on this functionality must have the ability to:
    1. pause and resume, to consume the content at a pace which suits them;
    2. go back to the beginning to replay the content with a single action; and
    3. rewind to hear a specific part again, or fast-forward past bits they have already heard.

It's fine for the standard audio player-style controls to be hidden until speech has been started for the first time.  But the functionality must be present, rather than just a single binary choice button which isn't going to be particularly useful to some users.

**Comment by alexrcabral** [comment]
Just to recap on the agreement from the Accessibility Meeting yesterday, we're good to go to development on the TTS and TTS settings with the current iteration, with the understanding that we will touch base in the future (first time four weeks from now) about testing other ways of surfacing audio controls, particularly regarding more complex prompts. 

Example: https://mathshare-qa.diagramcenter.org/#/app/problem/edit/UIRTIN267IV6C

**Comment by alexrcabral** [comment]
And to confirm @jscholes' second point -- rather than aria-pressed, we will move forward with explicit labels based on action: 

1. "Speak Prompt" for speaking the prompt
2. "Speak Step N" for each given step
3. "Speak My Work" for the my work section denoting the current editable step

Along with the accompanying 
1. "Stop Speaking Prompt"
2. "Stop Speaking Step N" 
3. "Stop Speaking My Work"

**Comment by jscholes** [comment]
@alexrcabral Right on.

**Comment by abaranowska1** [comment]
**Tested with success**

- hover state of inactive button
![image](https://user-images.githubusercontent.com/61964176/86326516-1d14fe80-bc42-11ea-84e3-711c7663afdf.png)
![image](https://user-images.githubusercontent.com/61964176/86326931-ae847080-bc42-11ea-99a7-465ec81d087b.png)

- hover state of active button
![image](https://user-images.githubusercontent.com/61964176/86326506-18e8e100-bc42-11ea-8849-27f9f9e87fd9.png)
![image](https://user-images.githubusercontent.com/61964176/86326939-b217f780-bc42-11ea-9986-50d9c761dee3.png)

- TTS buttons are added and it is possible to Speak or Stop the Prompt, Step, My Work.

The issue with TTS button for My work is mentioned in #997
