### ISSUE TITLE
Choose TTS speed

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1006]
Users can select the TTS speed.  Ranges from 0.5 to 2.5 speed.

**Comment by benetechMatt** [comment]
![mockup of the speed selection setting. "Voice speed" with a drop down of options. Toggle in the right column for quick settings](https://user-images.githubusercontent.com/49413678/75719964-52f9a480-5c9b-11ea-8547-3855eef7dd98.png)

0.5
.75
1
1.25
1.5
1.75
2
2.25
2.5

**Comment by benetechMatt** [comment]
changing the quick settings toggle to a checkbox

**Comment by alexrcabral** [comment]
@benetechMatt Does this need to be a discrete dropdown? Or can it be defined linearly? Most TTS systems and screen reading systems use linear sliders for more granular control

**Comment by jscholes** [comment]
@alexrcabral is right on the money here.  If you want to give a user value-based speeds, a slider is better and more recognisable.  If you want to give them quick presets, words like "Slowest", "Slower", "Normal", "Faster" and "Fastest" might be more usable.

**Comment by alexrcabral** [comment]
Everyone in agreement on call today to change this to a slider.

@benetechMatt is updating the mockup to a slider with the labels on either side as "Slowest" to "Fastest" (left to right)

**Comment by benetechMatt** [comment]
![mockup of slider with the setting name on the left. The slider has a label on the left that says "slowest" and a label on the right that says "fastest"](https://user-images.githubusercontent.com/49413678/78308349-e0841a80-750d-11ea-844d-58521043b570.png)

**Comment by jscholes** [comment]
CC @benetechMatt and @alexrcabral - Are you waiting for any further accessibility input from us on this one?

**Comment by alexrcabral** [comment]
Nope that covers it, thanks @jscholes! 

This is good to go with @benetechMatt's most recent mockup and description of the slider and the quick settings checkbox.

**Comment by alexrcabral** [comment]
Thanks for surfacing @rupeshparab, “Quick Settings” was a holdover from a previous set of issues so you can disregard it. 

And yes, the voice speed option should be added to our existing “Personalization Modal” so it would look like: 

<img width="646" alt="Mockup of Personalization Settings showing the options Font, Line Height, Letter Spacing, and Alert close time (in secs) with their corresponding drop-downs. This is followed by the new section titled Text to Speech with the option Speed followed by its corresponding slider control with the left labelled Slower and the right labelled Faster." src="https://user-images.githubusercontent.com/47576069/83815250-a3a2e400-a674-11ea-94b1-02ea05fd3b16.png">

**Comment by jscholes** [comment]
@alexrcabral What is the status of the personalisation modal?  Is it only at the design stage for now?

Also, should it be a modal?  Given our recent discussions about avoiding modal usage, particularly for content with many interactive controls, I really think this should be a page instead.

**Comment by alexrcabral** [comment]
For transparency on what we went over in the last accessibility call, the personalization modal has been in the live site since late 2019 (developed in October, released in December). We plan on looking at other ways on surfacing personalization in the future as a separate issue from TTS.

Somewhat related, we're also planning to move personalization from the profile dropdown into its own section on the universal header, so unauthenticated students can access it.

**Comment by johnhbenetech** [comment]
Hi @Sanjog1605 , can you recheck this. We made a recent update to modals which hopefully should fix this

**Comment by Sanjog1605** [comment]
Hello @johnhbenetech sir, I did check the change that was made in the modal, and following are my comments:

While reading/exploring using NVDA in Firefox as the browser, it seems to be working fine. Everything is as it should be. I also used the AXE accessibility extension in order to check if there are some contrast related problems, and while ding so, I found some issues:

1. According to AXE, the "arialabelledby" is not proper or it cannot recognize it.
2. There are still some contrast issues. Unfortunately, my vision restricts me to explore this issue. I deeply apologize. However, what one can do to begin with is to follow the WCAG Guidelines related to contrast, [Success Criterion 1.4.3 Contrast (Minimum)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html)

**Comment by johnhbenetech** [comment]
@alexrcabral please advise

**Comment by johnhbenetech** [comment]
Thanks @Sanjog1605 ! The contrast violation is related to a known issue #846 so hopefully that will be fixed in the near future.

@rupeshparab can you look into the arialabelledby. You are using 'ttsSpeed' which may have been removed during the design change and should be updated

**Comment by rupeshparab** [comment]
I have added the missing id on TTS speed heading

**Comment by johnhbenetech** [comment]
Sorry @rupeshparab, one more thing - can you change the background color of the save/close buttons to #0056B3

**Comment by rupeshparab** [comment]
I have updated the button color

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified cases:**
- TTS speed scroll bar was added to the Personalization Settings
- It is possible to change speed and save
- After save text is read slower or faster 
- The background color of the save/close buttons are changed to #0056B3
- ![image](https://user-images.githubusercontent.com/61964176/88036060-5060f400-cb43-11ea-839d-060cc23019d1.png)

**Verified on:**
- Google Chrome, Version 84.0.4147.89
- Firefox Version 78.0.2

**Comment by alexrcabral** [comment]
@rupeshparab I have noticed another small issue which came up during user testing. The QA version does not include the percentage (%) as was presented in the mockup and scoping on PR #1261 

<img width="728" alt="Mockup of Text to Speech speed setting in context, listed under the Text to Speech heading below General personalization settings. Next to the slider bar is a text box with the text 50%." src="https://user-images.githubusercontent.com/47576069/86065118-ae5a5a00-ba23-11ea-8b57-9659a5873611.png">

The percentage sign needs to be present (standard interaction of not selectable/deletable when the number is selected or deleted) as it contextualizes the information given by the number

**Comment by rupeshparab** [comment]
I have added %, but because we are using a number input and not a text input the '%' character will be at a fixed position in the input
Attaching screenshots
Chrome:
![image](https://user-images.githubusercontent.com/6897505/88305867-a4c4c900-cd27-11ea-8047-f8d33b2c54bc.png)

Firefox:
![image](https://user-images.githubusercontent.com/6897505/88305910-b4441200-cd27-11ea-9c60-7d74c8fa658e.png)

**Comment by abaranowska1** [comment]
**Tested with success**
I confirm that "%" character was added.
Chrome: 
![image](https://user-images.githubusercontent.com/61964176/88372551-6adedb80-cd96-11ea-99d3-2d6c8cbcad44.png)
Firefox:
![image](https://user-images.githubusercontent.com/61964176/88372563-703c2600-cd96-11ea-86e5-2b43e14d90e0.png)
