### ISSUE TITLE
Create content for "Getting started" page

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1082]

**Comment by benetechMatt** [comment]
Content for the getting started page https://benetech.box.com/s/m040cviwz5vvqnpmb5qo1nqbf0ku2fut

**Comment by jscholes** [comment]
@benetechMatt While iconography vs text is an entire discussion in itself, we do need to ensure that we're never only referencing iconography in documentation.  For example:

> Select the “trash” icon on the problem you wish to remove

This button has an accessible label as well, so that text needs to be referenced so a screen reader user can follow along.

> Select “yes” to confirm you want to delete it or “cancel” if you changed your mind.

This ties in with discussion from #968.  To fit in with user expectations and the UIs they'll be familiar with, this should be a yes/no question not yes/cancel.

> Click and hold on a problem and drag to re-order. Changes are automatically saved.

This document can't say anything about how to do this in an accessible way, because #764 is still outstanding.  Maybe one to discuss on a call?

> Learning Systems Integrated:

This should be a heading.

I have one critical question: will the content to be displayed be chosen based on a user's role?  At the moment, you have multiple H1s - one for educators and one for students.  When implemented, the page needs to have a single H1 and the rest of the structure must follow from that.

**Comment by benetechMatt** [comment]
Thanks @jscholes I’ll update the content regarding these points.  Same content for all users so I will adjust the headings and some of the organization

**Comment by benetechMatt** [comment]
Changed content significantly. Fixed heading issues. Removed references to iconography.

**Comment by jscholes** [comment]
@benetechMatt You have "How to Create a problem Set" listed twice, as a consecutive H2 and H3.  In addition, every single heading bar one in this document begins with the first two words ("how to..."), which is incredibly frustrating for screen reader users.  The headings make sense without them.

For this text:

> You may also create a new problem set by opening the “Help” button menu and then selecting “Create a Problem Set”

To reduce verbosity and cognitive load, this doesn't need to be inside a child nested list because it's just one item.  So:

> From the Mathshare dashboard, select “Create a Problem Set”.  You may also create a new problem set by opening the “Help” menu and then selecting “Create a Problem Set”.

Should we discuss the reordering/sorting controls on an upcoming call?

**Comment by benetechMatt** [comment]
Good points on the headings @jscholes. I’ll make this changes

Would you clarify what you mean by the rendering/sorting controls?

**Comment by jscholes** [comment]
@benetechMatt The reordering/sorting controls for arranging problems within a set.  See #764.

**Comment by benetechMatt** [comment]
content updated. Will need to review for changes with each release for feature or accessibility changes

**Comment by alexrcabral** [comment]
Closing this issue since basic content is complete. #1083 and PR #1213 encompass the code changes along with further revisions.
