### ISSUE TITLE
change wording to duplicate problem set menu option

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1130]

**Comment by benetechMatt** [comment]
All users should be able to duplicate problem sets on the /edit/, /view/, and /solve/ views of a problem set. This is designed to allow users to accomplish the following:
- owners of the set that want to make a new copy
- educators that want to make a copy of a problem set created by someone else

Keep the same icon
Current: "Duplicate set"
New: "Duplicate set in order to edit or assign"

![Mockup of the changed text.  Text wraps onto two lines](https://user-images.githubusercontent.com/49413678/79222598-7462ba00-7e1d-11ea-9c83-4c9bc6baebbc.png)

**Comment by benetechMatt** [comment]
change copy to "Duplicate to edit/share"

**Comment by johnhbenetech** [comment]
@benetechMatt Can you specify exactly what happens when this button is hit in each of these cases?

* The '/view' view doesnt really exist. It just immediately sends you on to your own solve version - not sure how this task is relevant there.

* The '/edit' case is clear to me - just basically changing the copy

* For '/solve' it sounds like at a minimum we need to add the 3 dot menu with this option. What does this button do in the case where you've already started solving the problems? Does it just send you to an editable version of the problem set as you originally received it? Does it send you to an editable version of the problem set that now also includes the work you've added thus far?

**Comment by benetechMatt** [comment]
For /edit it will make a copy of the set and you will be taken to that new copy to work on

For /solve it makes a copy of the set as it currently is, not how it was first opened. Any work you’ve added is also in the new copy that is made for you.  You are then taken to the /edit view of the set

________________________________

**Comment by jscholes** [comment]
Surfacing this as an issue which has not undergone accessibility review, but is marked as ready for development.

CC @alexrcabral

**Comment by alexrcabral** [comment]
Since #1167 was approved and merged, moving into Product Sign-Off

**Comment by abaranowska1** [comment]
**Tested with success**
- Name was changed to "Duplicate to edit/share"
![image](https://user-images.githubusercontent.com/61964176/82560182-39b51580-9b71-11ea-97c4-0810225eac47.png)
![image](https://user-images.githubusercontent.com/61964176/82560191-3de13300-9b71-11ea-8c06-889d4423c848.png)
![image](https://user-images.githubusercontent.com/61964176/82560205-45a0d780-9b71-11ea-8ed3-16b3c6098f0c.png)
- For /edit it makes a copy of the set and you are take to that new copy to work on
- For /solve it makes a copy of the set as it currently is, not how it was first opened. Any work we’ve added is also in the new copy that is made for us.  We are then taken to the /edit view of the set
