### ISSUE TITLE
deleting sometimes results in unintended removals

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#116]
trying to delete out the fraction bar to just simplify to b results in auto-deletion of the numerator b too

![image](https://user-images.githubusercontent.com/7883873/40811020-7b2697ca-64e4-11e8-838d-7b14223b7325.png)

**Comment by NSoiffer** [comment]
You shouldn't be able to select the faction bar... and I haven't found a way to do. The comment on step 5 says that sometimes the numerator gets deleted when selecting the fraction, but the example doesn't show that.

I think there is a separate issue of being able to cancel out a denominator and have the denominator (and fraction) go away on cleanup. However, for this issue, I don't think I can do anything because I can't replicate what you say sometimes happens for you.

**Comment by sueannma** [comment]
can't seem to reproduce anymore, so closing
