### ISSUE TITLE
ability to edit specific steps in the history (not just the last step)

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#118]
This has been requested several times, where a student might be on step 5 and noticed a slight error in step 2 and would like to go back and edit. We need to walk through a few scenarios and figure out the UI/UX for this experience, such as when something is changed in Step 2, 

- should it automatically trickle down to subsequent steps? 
- should this only apply in some cases?  
- should everything have to be manually applied? **(leaning towards this option to start)**

**Comment by johnhbenetech** [comment]
My opinion is that for right now the edit only effects the single step.

**Comment by afijal** [comment]
@johnhbenetech Just to ensure, edit affecting single step is our choice for now?

**Comment by johnhbenetech** [comment]
The coresponding button should say 'Edit' and can use the font awesome 'pencil' icon

**Comment by pawelcieszko** [comment]
@johnhbenetech I'm working on this issue and I have a question about cleanup functionality while editing. Currently, the math steps are sequentially numbered (cleanup row is numbered separately).

Case:
There are 4 steps without cleanup (no cross-outs) . A user wants to edit step no. 2 and make some cross-out. Should an additional cleanup row be added? It's slightly problematic due the fact that it will change the current step order (1,2,3,4). Moreover, there are some next calculations (step 3 and 4) so in my opinion the additional cleanup row is not necessary.

**Comment by johnhbenetech** [comment]
I didnt catch this before, but in #128 i think maybe in addition to removing the visible label associated with a cleanup, we should have also prevented clean up steps from incrementing the step count.

cleanup/calculate steps should not be considered a real step i think, because they are largely machine actions.

Feel free to break this out into another task. Once that's in place hopefully that makes the edit function clearer. If a user edits step 2 of 5, but adds a calculation in that step - the steps will not need renumbering because the calculate doesnt increment the count.

If a user edits a previous step that already had a calculate/cleanup associated with it, the original cleanup row should be removed, and re-added if needed after the user saves their edits (if they still have a calculate for instance).

**Comment by sueannma** [comment]
Yes, what John described is what we had in mind. The cleanup/calculate should not increment an additional step since this would be part of a "set" of work applied by the student.

**Comment by pawelcieszko** [comment]
Thanks for the response. I have created a new issue #192

**Comment by dserkowski** [comment]
I have tested it. It looks ok
Results:
* there is a possibility to edit specific row by the button with 'pencil'  button
![1](https://user-images.githubusercontent.com/29867015/41964221-c25ba840-79f9-11e8-86af-380fd6d478fe.png)
* after clicking the button the editor moved to the specified row. There is an option to apply or discard changes 
![2](https://user-images.githubusercontent.com/29867015/41964243-cba759f8-79f9-11e8-98e1-a8687dfe1c10.png)
