### ISSUE TITLE
Add digital scratch pad

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#120]
the scratch pad should also have some way to change color, size, drawing tool, etc. (see Khan Academy for an example); refer to design mocks for interface: 
![image](https://user-images.githubusercontent.com/7883873/40878186-335cb7ee-6642-11e8-9466-5c9753829161.png)

**Comment by johnhbenetech** [comment]
Do we imagine this being one scratch pad per problem? Or should we afford a new scratchpad per step?

**Comment by johnhbenetech** [comment]
Let's make it a scratchpad per problem (these should start blank at this stage).

It might be beneficial to use an existing scratchpad that has the ability to include image upload, but we can revisit this later (related to #145)

when we eventually add the backend, these images will need to be stored in a database/file system. For the time being these can be ephemeral and only temporary in the cache.

**Comment by pawelcieszko** [comment]
@johnhbenetech What do you think about the scratch pad? Currently, the functionality seems to work properly. However, we are not sure if the layout looks as expected

![image](https://user-images.githubusercontent.com/29859787/42170533-1cc3168a-7e17-11e8-8392-fd2f91df722b.png)

**Comment by kkrawczyk123** [comment]
I have noticed that Display/hide sketch pad and Add Step buttons are placed on the same level but when one of the added steps is deleted and Undo Last Delete arrow is visible, Add Step button is placed a bit lower. I think that it would be good to unify that those buttons would be placed on the same level independently on Undo Last Delete Arrow.
Screenshot attached:
![screenshot from 2018-07-18 11-52-54](https://user-images.githubusercontent.com/33342488/42874681-fe5e1cd6-8a81-11e8-984e-11d817e64e64.png)

**Comment by johnhbenetech** [comment]
I think we are in a pretty good place where we essentially might need to iterate on certain features, but we can close this task as complete.

@kkrawczyk123 I still don't like the button arrangement in the 'My Work' section, so I'm going to try to get some UI/UX opinion from our side. My goal is trying to get the height of the My Work section as small as possible (even when the sketchpad is being used) so that more of the work history can be seen especially on lower resolutions screens. I will break out that into a backlog task.
