### ISSUE TITLE
Step automatically calculated/cleaned up by accident

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1203]
While working through this population growth problem, mathshare automatically calculated my step and gave me an answer in the "cleanup" step.  I used the stack below tool to put the equation below variable values 
https://mathshare.benetech.org/#/app/problemSet/edit/3B43DA3EJC4A2/3

**Comment by johnhbenetech** [comment]
It seems that stack below is being interpreted as "add the two lines together", you can see this using simple integer examples. I'm not sure exactly how it interprets letters and variables into values to add, but it does in some way

**Comment by alexrcabral** [comment]
Could you take a look at this issue on the QA side to try and figure out the specifics on what is happening with this bug?

**Comment by abaranowska1** [comment]
@benetechMatt 
I tried to reproduce this bug on QA environment, but I can't. Could you give me a reproduction steps or record a gif?

**Comment by abaranowska1** [comment]
I noticed such things on Firexof Browser ( v.76.0.1 ) when I marked for example 31,771 and click "stack below" button, add 2 and add the step I get 773 which is false. When I marked the whole expression and use stack below with "2" I get the interesting thing P=31,711//2.
Also I met an issue on Firefox, because I cannot delete values from "my work" using "Backspace or Delete" keyboard buttons. 
![Peek 2020-05-25 15-52](https://user-images.githubusercontent.com/61964176/82819329-7d28c000-9ea0-11ea-9629-97f791a06676.gif)
https://mathshare-qa.diagramcenter.org/#/app/problemSet/edit/PT4QVYZ52M3GI/0

**Comment by johnhbenetech** [comment]
@abaranowska1 can you look a bit more into the backspace/delete/undo issues (are they caused by stack below? Do they happen in other browsers?) Then if needed create a separate task for them

**Comment by johnhbenetech** [comment]
@alexrcabral please let us know how you'd like to proceed

**Comment by abaranowska1** [comment]
@johnhbenetech I created a new task https://github.com/benetech/MathShare/issues/1214 it occurs only on QA instance

**Comment by alexrcabral** [comment]
@johnhbenetech is the calculation happening on our side or on the MathLive side?

Since there are no standard calculations inherent in stack below, ideally to proceed we should adjust the "clean up" stage so it does not affect stack below. 

This should result in all the lines involved in stack below being brought down to the following step.

**Comment by johnhbenetech** [comment]
@rupeshparab can you look into the cause of this?

**Comment by alexrcabral** [comment]
Looks good now, thanks for getting to the bottom of it @abaranowska1 and @rupeshparab!

**Comment by abaranowska1** [comment]
For me it also looks good now, step is not automatically calculated/cleaned up by accident 
![Peek 2020-05-29 08-53](https://user-images.githubusercontent.com/61964176/83230389-f880bf00-a189-11ea-8f04-3711b8a6cdc5.gif)
