### ISSUE TITLE
Cannot copy paste math from previous steps

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1262]
Users need to be able to copy math equations from previous steps and paste it into the editor.  A use case would be complex solutions where users need too re-use an equation from a previous step that is no longer in the editor.

**Comment by alexrcabral** [comment]
Example: 

<img width="1071" alt="Screen shot of Mathshare of the problem 'solve for x and y: 2x plus 4y equals negative 10, and 6x plus 3y equals six.' The math displayed in the math editor, x equals negative 2y minus 5, is currently highlighted." src="https://user-images.githubusercontent.com/47576069/85476934-28936600-b56e-11ea-81e4-ef7389eff221.png">

The first equation is solved for x, but in order to finish the problem the second equation needs to be copy-pasted from the original question to work through it. 

The math displayed on previous steps should be able to be highlighted in order to copy and paste them into the math editor.

**Comment by rupeshparab** [comment]
I have added readonly mathlive editors in step to allow selection of text, but it has few limitations. In case of math which has multiple lines, it won't allow partial selection of text, it will automatically select the entire line

**Comment by johnhbenetech** [comment]
@Sanjog1605 Hopefully this didn't break anything on the a11y front, but I want to make sure you review it. Basically it's a small change to the mathlive call changing the way the math in the my steps section is rendered. Let us know if you experience any regressions.

**Comment by Sanjog1605** [comment]
After going through the comment given by @alexrcabral sir, I have checked whether one can copy and paste the equations or not. Following are my observations:

* I was able to copy and paste the equations into the next step.
* When the next step is created, the equation from previous step remains, I presume for easier editing and continuing the work without interruption/hurdle.

However, I was unable to find any kind of highlighted equation as @alexrcabral  sir mentioned in the above comment. @johnhbenetech  sir, kindly let me know if my understanding is correct or there is something that I may have missed out.

**Comment by alexrcabral** [comment]
The highlighting mentioned was in reference to selecting text and the associated visual highlighting, which i was able to do both independently with mouse and independently with keyboard

**Comment by Sanjog1605** [comment]
Hello @alexrcabral sir, I checked the highlighting, and it's working fine.
Thank you

**Comment by abaranowska1** [comment]
**Tested with success**
I checked the copy-paste function from previous steps and also the possibility of highlighting by mouse and keyboard.
- I was able to copy and paste the equations into the next step.
- I was able to highlight text independently with mouse and independently with keyboard

**Tested on:**
- Ubuntu 20.04
- Google Chrome Version 85.0.4183.83
