### ISSUE TITLE
Subscripts aren't read in TTS

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#1279]

**Comment by johnhbenetech** [comment]
I've logged an issue to mathlive: https://github.com/arnog/mathlive/issues/534

**Comment by rupeshparab** [comment]
@johnhbenetech 
I was trying few more speech configuration options from https://github.com/arnog/mathlive/blob/cc1194548b6735485241dde8483f7e88c130b2eb/src/public/config.ts

while using 'mathlive' in textToSpeechRules along with 'clearspeak', everything seems to be read out correctly

![image](https://user-images.githubusercontent.com/6897505/86952244-52ed4200-c170-11ea-88d2-6235ac0fc0a7.png) is read as '3 sub 2'

![image](https://user-images.githubusercontent.com/6897505/86952359-80d28680-c170-11ea-9d0c-5f87a33fa829.png) is read as 'crossed out 2 plus 2. End cross out to the capital A;'

you can merge this PR to try it: https://github.com/benetech/MathShare/pull/1288

**Comment by johnhbenetech** [comment]
Interesting, I think the only weird thing is that what every is in the 'replace' portion is read as a power. So like if you replace something with a 3 it get read as 'crossed out something end cross out cubed'

@rupeshparab I assume the cross out and replace is something MathShare hacked together (rather than supported by mathlive). So i assume somewhere in the codebase we tie that button to the exponent function?

If that's the case we may need a recommendation from @alexrcabral on how to handle cross-out vs. cross-out and replace from a generated MathML perspective

**Comment by rupeshparab** [comment]
right @johnhbenetech , crossout and replace is our own implementation where we are manipulating the latex ourselves

**Comment by johnhbenetech** [comment]
what do you think @alexrcabral? So whenever we added the cross-out and replace, for whatever reason, we used the exponent to achieve it. 

How would you recommend we move forward? If we change it to just put the cursor next to the cross-out it becomes the same as the cross out button. Do we need both?

**Comment by alexrcabral** [comment]
Ideally if possible within MathLive/MathML, we would be able to show the replaced number as a constant. 

With focus: 
<img width="191" alt="Mockup of crossout, 7x minus 13, end cross out, blank, equals zero. The blank portion is outlined by a dotted square the size of a constant, and highlighted in blue." src="https://user-images.githubusercontent.com/47576069/87229821-4deee500-c360-11ea-9389-d0ef163f0025.png">

Without focus: 
<img width="190" alt="Mockup of crossout, 7x minus 13, end cross out, blank, equals zero. The blank portion is outlined by a dotted square the size of a constant, with no highlighting." src="https://user-images.githubusercontent.com/47576069/87229829-57784d00-c360-11ea-9bbe-e0d244b11c4f.png">

Having the "replace" portion is helpful for students who may otherwise be worried about removing numbers instead of simplifying them, particularly if they have memory or cognitive difficulties. E.g. if they cross out 2/4 will they remember to replace it with 1/2? 

However, based on our earlier discussion @johnhbenetech, if this isn't possible within MathLive/MathML and the reason it was presented as an exponent in the first place was the next best workaround, then we should remove Cross Out & Replace entirely.

**Comment by johnhbenetech** [comment]
@rupeshparab can you explore using cross out and replace using the \boxed or \bbox markup which is available via mathlive? Right now it breaks a lot of stuff including nothing being read after the box and even subsequent steps breaking due to the boxed content. I assume it's being handled weirdly in the LaTeX to mathml conversion.

**Comment by johnhbenetech** [comment]
I'm removing the irrelevant discussion to this task to the proper task #1282. This task will move to QA as it is handled

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
- QA env
- Browsers
-- Chrome v83.0.4103.116
-- Firefox v78.0.2

**Verified cases**
- TTS for subscripts
- TTS for superscripts

**Summary**
Subscripts and superscripts are read. The cross out and replace is read as a superscript, but I believe it will be resolved in #1282
