### ISSUE TITLE
Remove Log in pop-up

### ISSUE THREAD

**Issue by alexrcabral** [benetech/MathShare#1290]
Problem: The log in pop-up which was recently added (Ref: #973) is overly intrusive from an accessibility standpoint, a usability standpoint, and a partner standpoint. As an unauthenticated user, I want to be able to continue my process uninterrupted. 

Solution: The Log In Modal (example below) should not pop up when accessing a problem set.

<img width="613" alt="Screen shot of Log In modal showing login options, benefits of signing in, and an option to continue without signing in. In the background is a greyed-out example problem set." src="https://user-images.githubusercontent.com/47576069/87105554-2be64d00-c210-11ea-9e3c-aaf5328002c7.png">

Acceptance Criteria: 

Scenario 1: Given I'm an unauthenticated user, when I click on an example set or click to create a problem set, then I will be taken directly to the set (without the explicit modal prompting to log in).

Scenario 2: Alternatively, given that I'm an unauthenticated user, when I access mathshare through a link to a particular problem set or problem, I will be directed to the page itself rather than presented with the log-in modal.

**Comment by johnhbenetech** [comment]
@rupeshparab this is reverting a previous change

**Comment by bognasoldev89** [comment]
This modal is indeed not available on the problem set anymore. But as far as I recall it popped up on the homepage as well and it is unclear to me if on the homepage it should stay or not. @alexrcabral @johnhbenetech 
I'm referring to the homepage with the list of pre-made sets, link to problem sets creation, etc.

**Comment by johnhbenetech** [comment]
@alexrcabral can we get a response on this. I'd like to move it past QA

**Comment by alexrcabral** [comment]
@bognasoldev89 The original issue which made it appear was #973, which specified it as tied to the problem set link (reverted here). I don't recall it popping up on the welcome page or the homepage, unless log in or sign up was explicitly clicked, and testing it now also has the expected behavior (no pop-up unless explicitly clicking the log in or sign up buttons). 

Do you have an example of an unprovoked popup occurring on the welcome page or the homepage? And under what circumstances?

**Comment by bognasoldev89** [comment]
@alexrcabral that was what I recalled but since all of those changes are reverted I am not able to try to provoke this behavior to check. I wanted to make sure this pop-up is in place in every place on the app.

Since this behavior is correct I cannot see why this issue couldn't be moved to done.

**Tested with success**

**Environment**
- QA env
- Browsers
-- Chrome v83.0.4103.116
-- Fireforx v78.0.2

**Verified cases**
- Opening the app as not logged in user and observing for log in pop-up on the:
-- welcome page
-- homepage
-- problem set page
-- problem page
-- create problem set page
- Copying the link and pasting it as not logged in user

**Summary**
Not wanted login pop-up was not spotted in any case.

**Attachments**
![ms 1290](https://user-images.githubusercontent.com/51324797/87789918-112f5c00-c840-11ea-8776-a75ddf67b63e.gif)

![ms 1290 chrome](https://user-images.githubusercontent.com/51324797/87789921-12f91f80-c840-11ea-91ec-ff99600fac82.gif)
