### ISSUE TITLE
issues changing tts speed from text box

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1330]
In the TTS speed % text box, if the number is deleted it keeps a 0 in the box so instead of 60% it's 060% when only using the keyboard.
Pressing delete multiple times quickly doesn't always delete everything in the box. It deletes one number and then stops until I stop pressing delete, pause, and press delete again.
Up and down arrow keys within the TTS text box does change the % but the keys must be pressed slowly.  Pressing them rapidly up or down does not change for each key press.  pressing the up arrow 10 times quickly will only change the % by 1 instead of 10.
Video of issue
https://www.loom.com/share/aab26df6303f4f079d1523412a48f93a

**Comment by bognasoldev89** [comment]
I think adding the field validation could be added to the scope of this issue. As @benetechMatt noticed the provided value can be higher than 100 and the effect is ridiculous.

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
- QA env
- OS
-- Ubuntu 18.04.4
-- Windows 10
- browsers
-- Chrome 83.0.4103.116 
-- Firefox 79.0

**Verified cases**
- providing number from 1-100
- providing number starting with 0
- providing number higher than 100
- providing comma, minus

**Summary**
TTS speed field is validated in every way. Only integers from 0-100 can be provided.
Note: after providing comma, on the Chrome the value provided before it stays, and on Firefox the number changes to 0. It has no impact though since the user cannot provide comma into this field.

**Attachments**
![ms 1330](https://user-images.githubusercontent.com/51324797/90033634-f8d82300-dcbf-11ea-9c2a-77bb23a8c908.gif)
