### ISSUE TITLE
Hook up clear all functionality to button

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#161]
Clear all should remove all steps except for the original problem definition.

**Comment by oskarhinc** [comment]
During the implementation of this functionality, I've found out that original problem definition (step 1) can be deleted. I believe it's not expected behavior, because 'delete' button is not visible at the beginning, but only when step 2 was deleted. If it's a bug I could fix it as a part of this issue. Similarly - how to deal with 'clear all' button when there's only step 1 provided?

**Comment by johnhbenetech** [comment]
Your instincts are correct. I imagine this will change after #151 , but should still be fixed until then.

I think ideally:

* clear all should leave the first step as it was originally
* clear all should essentially do nothing if only the first step is available (i dont think we should disable it for now)
