### ISSUE TITLE
Problem with CSS loader on the Windows

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#503]
While trying to build the front-end application on the Windows, there are errors that stem around not having an ‘appropriate loader’ to handle the CSS. Investigate the issue and fix it, or update the read.me file if the problem is related to the environment.

**Comment by johnhbenetech** [comment]
I believe i fixed this for now. 
https://github.com/benetech/MathShare/commit/55a4e6160ba33ff6bd3429902f1bdee5d525e71e

I updated the regex to look for either style of directory separator and it seems to work. I also added a eslintignore file to explicitly ignore the mathlive directory  since the ignore line in the eslintrc file didn't seem to be working for me.
