### ISSUE TITLE
Make recommendations for spaces in text input

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#514]
Any suggestions how we might try to fix the issue where you are unable to enter a whitespace in text input in my work?

I realize this probably bridges into mathlive territory, but even if we can't fully implement it I would like to have a record of some options you guys think might be good to explore.

**Comment by oskarhinc** [comment]
@johnhbenetech unfortunately, we haven't found a way to insert whitespace in text input in MyWork section, but I've found a solution to handle it in a different way. I've already implemented it and created a pull request, but we haven't merged it yet as we would like to confirm if it's expected behavior - https://github.com/benetech/MathShare/pull/516. 

I've overridden the MathLive behavior when Spacebar is pressed, so it inserts whitespace when it's not in command mode:

![screenshot from 2018-09-20 14-22-34](https://user-images.githubusercontent.com/19305104/45817984-a6af4280-bce0-11e8-859d-3cc74eb6f14f.png)

but when spacebar is detected, after we pressed 'input text' button, but before we left the command mode - spacebar confirms the command, add a whitespace outside the command mode, and reopens the text input mode. In this case:

Before pressing the spacebar:
![screenshot from 2018-09-20 14-26-41](https://user-images.githubusercontent.com/19305104/45818216-5c7a9100-bce1-11e8-8490-d196fc15970d.png)
Right after spacebar is pressed:
![screenshot from 2018-09-20 14-26-49](https://user-images.githubusercontent.com/19305104/45818235-67cdbc80-bce1-11e8-9e81-85188ac4f077.png)
after the rest of the text is inserted and the command is finished:
![screenshot from 2018-09-20 14-27-01](https://user-images.githubusercontent.com/19305104/45818265-7b792300-bce1-11e8-96f6-5a17de39d951.png)

This solution might cause unwanted behavior when a user leaves the command without its confirmation - I can show it to you at the meeting.

Another solution is to insert a special string in the text input field - e. g. '<SPACE>', and replace it after the command is executed:
![screenshot from 2018-09-20 14-43-26](https://user-images.githubusercontent.com/19305104/45819025-9482d380-bce3-11e8-8068-7f540909e58c.png)
But it obviously has disadvantages too.
