### ISSUE TITLE
Add a “previous problem” button to the bottom of the screen

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#969]

**Comment by benetechMatt** [comment]
![mockup of the problem solving screen. at the bottom, below the math editor tools palette there are three buttons. In the middle is "finish" which currently exists.  On the left is a button with a left arrow and the text "previous problem". The button is on the far left side of the screen in the same row as the other two buttons. On the right is a button with a right arrow and the text "next problem"](https://user-images.githubusercontent.com/49413678/75600009-041bf700-5a70-11ea-87b8-fddb6eb51815.png)

**Comment by alexrcabral** [comment]
Depends on the student. If they like more steady, consecutive work and want to finish problems before moving on to the next, they might use the finish button more. But if they like to jump around between problems, connect patterns, or complete the same step of each problem, they're going to use next problem more frequently. 

I think the way it is laid out in the mockup is fine.

**Comment by johnhbenetech** [comment]
I assume previous and next will be disabled for the first and last problem respectively?

Or do you want it to cycle?

**Comment by alexrcabral** [comment]
@johnhbenetech The "next" and "previous" buttons should be visibly inactive (eg greyed out) and not able to be interacted with for non-applicable pages. First problem should not have an active "previous" button, last problem should not have an active "next" button.

**Comment by jscholes** [comment]
@bpmcneilly may have more thoughts, but a couple of notes from me:

1. The contrast issue discussed in #968 also applies to the "Finish" button here.
2. We need to be careful when disabling buttons which a user has just activated (see below).

#### Inactive Buttons

When a user uses the prev/next buttons in a way which results in the focused one being transitioned to a disabled state, keyboard focus will seem to disappear and become undefined.  This is because programmatically disabled controls cannot receive focus, and is problematic for anyone relying on a predictable focus point and visible indicator (basically all keyboard, switch control and speech input users).

To achieve the behaviour as outlined, the only solution to this problem is to avoid using the `disabled` attribute on the buttons.  Instead, `aria-disabled` should be used, along with a `tabindex` of `"-1"` when a particular button can no longer be activated.  The click event handler should then return immediately to act as a no-op for a disabled button, and appropriate styling can be added to visually indicate state.

However, this pattern fundamentally goes against the use of appropriate mark-up and native attributes.  We can provide more details if required, but the simplest solution would be to allow the set to continue rotating endlessly in each direction.  That is, Pressing the previous button from the first problem would move to the last and vice versa.  This would remove the need for disabled buttons and the convoluted arrangement outlined above altogether.

**Comment by benetechMatt** [comment]
I'm in favor of rotating through problems as it also makes it easier for students to review problems they've already worked on.


Currently the problem number isn't displayed.  This should be added so students know when they have begun looping through the set again. #1060

**Comment by sinabahram** [comment]
Totally agree to this. I just want to flag that it’s critical for students to know current problem number, and also “out of” how many there are.

**Comment by johnhbenetech** [comment]
As discussed on call:
* First problem will not render 'Previous Button'
* Last problem will not render 'Next Button'

**Comment by jscholes** [comment]
Appreciating that we weren't able to join today's call, I'd still like to understand the thinking behind the decision and exactly how it will behave.  We seem to have gone from disabled buttons, to endless rotation, to no buttons at all, in a fairly short period of time.  If the prev or next button simply won't be rendered for the first or last problem, focus will stillneed to be managed when the button disappears, and I don't really know where the best place for it would be.  A button just vanishing sounds jarring in general.

**Comment by johnhbenetech** [comment]
Assigning to @alexrcabral for comment

**Comment by johnhbenetech** [comment]
We will go with disabled button approach due to lack of communication from product team

**Comment by abaranowska1** [comment]
"Previous Problem" button was added to the bottom of the screen and "wrap around" rotating button approach was used
![image](https://user-images.githubusercontent.com/61964176/82318554-57974480-99d0-11ea-94cc-b63702d07521.png)
